// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lujduuqsrkxjfschhswp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1amR1dXFzcmt4amZzY2hoc3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNTg3MjAsImV4cCI6MjA1MzczNDcyMH0.V8x9GYJwmBv1xwIy5PEAvfi6wANSrl1DpZ1r9UhlL10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);